### ISSUE TITLE
HELLO, I have a quession. Where is the file "neurofis.fis"

### ISSUE THREAD

**Issue by lhlhth** [DarthHyperion/BLDC-Fuzzy-PID#1]

**Comment by malifarooq** [comment]
As far as I am aware, there doesn't seem to be any dependency on `neurofis.fis`. That was used in an old version of the project. In this repo, the files `*_fuzzy2.fis`  each control their respective parameters. If there is any dependency, please let me know. It's been a while since I worked on this project.
